services:
  - type: web
    name: RotaTrabalhoMarcio
    env: python
    plan: free
    region: oregon
    branch: main
    rootDir: .
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1 --threads 4
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: RANDOMIZAR_ARESTAS_PROP
        value: 0.05
      - key: INIT_GRAPH_ON_START
        value: false
      - key: GRAPH_MODE
        value: graphml
      - key: GRAPHML_FILE
        value: /opt/render/project/src/data/marica_drive.graphml
